/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = function (knex) {
  return knex("Pets")
    .del()
    .then(function () {
      return knex("Pets").insert([
        {
          user_id: 2,
          name: "Max",
          species: "dog",
          breed: "Labrador Retriever",
          age: "4",
          description: "Friendly and loves to play fetch.",
          photo_url:
            "https://www.dogster.com/wp-content/uploads/2024/04/labrador-retriever-dog-standing-in-the-grass_Alexander-Rim_Shutterstock.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Rex",
          species: "dog",
          breed: "German Shepherd",
          age: "3",
          description: "Protective and loyal.",
          photo_url:
            "https://images.squarespace-cdn.com/content/v1/5baffc59fb182025fee90fef/92442d27-b354-4240-b998-bcbe0f1cd91c/German-shepherd-training-main.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Buddy",
          species: "dog",
          breed: "Golden Retriever",
          age: "5",
          description: "Loves to fetch and swim.",
          photo_url:
            "https://dogtime.com/wp-content/uploads/sites/12/2024/03/GettyImages-1285465107.jpg?resize=1200,630",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Bruno",
          species: "dog",
          breed: "Bulldog",
          age: "2",
          description: "Affectionate and courageous.",
          photo_url:
            "https://cdn.britannica.com/07/234207-050-0037B589/English-bulldog-dog.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Charlie",
          species: "dog",
          breed: "Beagle",
          age: "3",
          description: "Curious and friendly.",
          photo_url:
            "https://www.akc.org/wp-content/uploads/2021/01/Beagle-puppy-standing-in-the-grass-1.jpeg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Daisy",
          species: "dog",
          breed: "Poodle",
          age: "4",
          description: "Intelligent and elegant.",
          photo_url:
            "https://www.dogster.com/wp-content/uploads/2023/08/red-toy-poodle-in-the-park_Mykhaylo_Kozelko_Shutterstock-600x400.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Rocky",
          species: "dog",
          breed: "Rottweiler",
          age: "3",
          description: "Strong and protective.",
          photo_url:
            "https://cdn.britannica.com/69/234469-050-B883797B/Rottweiler-dog.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Bella",
          species: "dog",
          breed: "Yorkshire Terrier",
          age: "2",
          description: "Small and playful.",
          photo_url:
            "https://cdn.prod.website-files.com/61bcf7a199a6ef4fbfb9ee04/66e45a70380fdf8f4505eda2_EA8nH-38tNWSoSWGsknDRJvGMS3JLY84_UF-feghmeQ.jpeg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Max",
          species: "dog",
          breed: "Boxer",
          age: "4",
          description: "Playful and energetic.",
          photo_url:
            "https://media.graphassets.com/resize=height:404,width:718/output=format:webp/2zWkueuOSnin7luJKVrU",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Cooper",
          species: "dog",
          breed: "Dachshund",
          age: "5",
          description: "Loves to dig and chase.",
          photo_url:
            "https://www.akc.org/wp-content/uploads/2017/11/Longhaired-Dachshund-standing-outdoors.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Whiskers",
          species: "cat",
          breed: "Persian",
          age: "3",
          description: "Calm and enjoys being pampered.",
          photo_url:
            "https://images.squarespace-cdn.com/content/5e8a2944d7ce562e250eb009/1646832190680-GMPS3W54A2K2AMX8ABKQ/sergey-semin-6TiFuD_1q4o-unsplash.jpg?format=1500w&content-type=image%2Fjpeg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Sophie",
          species: "cat",
          breed: "Siamese",
          age: "2",
          description: "Affectionate and talkative.",
          photo_url: "https://example.com/photos/sophie.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Maine Coon",
          species: "cat",
          breed: "Maine Coon",
          age: "4",
          description: "Gentle giants that love to cuddle.",
          photo_url: "https://example.com/photos/maine_coon.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Ragdoll",
          species: "cat",
          breed: "Ragdoll",
          age: "1",
          description: "Loves to be held and is very affectionate.",
          photo_url: "https://example.com/photos/ragdoll.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Bengal",
          species: "cat",
          breed: "Bengal",
          age: "3",
          description: "Energetic and playful.",
          photo_url: "https://example.com/photos/bengal.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Sphynx",
          species: "cat",
          breed: "Sphynx",
          age: "2",
          description: "Loves attention and is very affectionate.",
          photo_url: "https://example.com/photos/sphynx.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Misty",
          species: "cat",
          breed: "British Shorthair",
          age: "4",
          description: "Calm and easygoing.",
          photo_url: "https://example.com/photos/misty.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Nala",
          species: "cat",
          breed: "Abyssinian",
          age: "3",
          description: "Active and loves to climb.",
          photo_url: "https://example.com/photos/nala.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Oliver",
          species: "cat",
          breed: "Scottish Fold",
          age: "2",
          description: "Playful and very social.",
          photo_url: "https://example.com/photos/oliver.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Lola",
          species: "cat",
          breed: "Devon Rex",
          age: "1",
          description: "Curious and loves to play.",
          photo_url: "https://example.com/photos/lola.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },

        {
          user_id: 2,
          name: "Polly",
          species: "bird",
          breed: "Parakeet",
          age: "2",
          description: "Sings and chirps happily.",
          photo_url: "https://example.com/photos/polly.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Sunny",
          species: "bird",
          breed: "Cockatiel",
          age: "3",
          description: "Friendly and loves to whistle.",
          photo_url: "https://example.com/photos/sunny.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Chirpy",
          species: "bird",
          breed: "Canary",
          age: "1",
          description: "Sings beautifully.",
          photo_url: "https://example.com/photos/chirpy.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Cupid",
          species: "bird",
          breed: "Lovebird",
          age: "2",
          description: "Affectionate and social.",
          photo_url: "https://example.com/photos/cupid.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Gigi",
          species: "bird",
          breed: "African Grey Parrot",
          age: "4",
          description: "Intelligent and talks a lot.",
          photo_url: "https://example.com/photos/gigi.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Bubbles",
          species: "bird",
          breed: "Budgerigar",
          age: "3",
          description: "Loves to chat and play.",
          photo_url: "https://example.com/photos/bubbles.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Rio",
          species: "bird",
          breed: "Macaw",
          age: "5",
          description: "Colorful and loves to socialize.",
          photo_url: "https://example.com/photos/rio.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Flick",
          species: "bird",
          breed: "Finch",
          age: "2",
          description: "Small and cheerful.",
          photo_url: "https://example.com/photos/flick.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Coco",
          species: "bird",
          breed: "Cockatoo",
          age: "3",
          description: "Loves to dance and play.",
          photo_url: "https://example.com/photos/coco.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Eddy",
          species: "bird",
          breed: "Eclectus Parrot",
          age: "2",
          description: "Very friendly and sociable.",
          photo_url: "https://example.com/photos/eddy.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },

        {
          user_id: 2,
          name: "Binky",
          species: "rabbit",
          breed: "Holland Lop",
          age: "2",
          description: "Sweet and loves to be held.",
          photo_url: "https://example.com/photos/binky.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Nibbles",
          species: "rabbit",
          breed: "Netherland Dwarf",
          age: "1",
          description: "Tiny and loves to explore.",
          photo_url: "https://example.com/photos/nibbles.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Flopsy",
          species: "rabbit",
          breed: "Mini Rex",
          age: "2",
          description: "Friendly and loves to hop around.",
          photo_url: "https://example.com/photos/flopsy.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Snowball",
          species: "rabbit",
          breed: "Lionhead",
          age: "3",
          description: "Fluffy and loves to cuddle.",
          photo_url: "https://example.com/photos/snowball.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Giant",
          species: "rabbit",
          breed: "Flemish Giant",
          age: "4",
          description: "Large and gentle.",
          photo_url: "https://example.com/photos/giant.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Fluffy",
          species: "rabbit",
          breed: "English Angora",
          age: "3",
          description: "Super fluffy and loves grooming.",
          photo_url: "https://example.com/photos/fluffy.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Cuddles",
          species: "rabbit",
          breed: "Mini Lop",
          age: "1",
          description: "Small and loves to snuggle.",
          photo_url: "https://example.com/photos/cuddles.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "BunBun",
          species: "rabbit",
          breed: "American Fuzzy Lop",
          age: "2",
          description: "Soft and loves to play.",
          photo_url: "https://example.com/photos/bunbun.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Hopper",
          species: "rabbit",
          breed: "Rex Rabbit",
          age: "3",
          description: "Active and loves to hop.",
          photo_url: "https://example.com/photos/hopper.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 2,
          name: "Harley",
          species: "rabbit",
          breed: "Harlequin",
          age: "1",
          description: "Playful and loves to explore.",
          photo_url: "https://example.com/photos/harley.jpg",
          pet_status: "available",
          posted_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
      ]);
    });
};
